allowBuilds:
  cpu-features: false
  esbuild: true
  node-git-server: false
  protobufjs: false
  ssh2: false
minimumReleaseAge: 11520
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
trustLockfile: false
blockExoticSubdeps: true
overrides:
  chokidar: 5.0.0
